### ISSUE TITLE
Todo App 요구사항 명세서 작성

### ISSUE THREAD

**Issue by jeein2222** [jeein2222/my-github-test-repository#1]
### 만들고자 하는 기능이 무엇인가요?
ex) Todo 생성 기능

### 해당 기능을 구현하기 위해 할 일이 무엇인가요?
1.  [ ] Todo 엔티티 작성
2.  [ ] Todo Controller 작성
3.  [ ] Todo Service 작성
4.  [ ] Todo Repository 작성
5.  [ ] Todo Mapper 작성
6.  [ ] DB 설정

**Comment by jeein2222** [comment]
Todo done!
